# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e06b01bd2e0ea56884d07bafb32e9a5267dd8472cd739f6c6be53b3dd1ac5c106cd6c58abf9da91eec9394fb3f648248ffa6ee4f8799a363decdb988cbad955

test:
  secret_key_base: a5a362511eddf4b2f002dd569ae48bdfd570c9f5f0d7c980e43f6518983ccc0a680a54a30de3ba14aa2b7ceb9df365a0f92ee51694f0d7c8d44829615d94480b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
